---

include: 
  - ./infra-docker-compose.yml

services:

  publisher:
    build: ./publisher
    environment:
      DEBUG_ON: no
  publisher_dapr:
    build: ./dapr
    command: /daprd -app-id publisher -app-port ${RECEIVER_PORT} --log-level debug --resources-path /components
    network_mode: "service:publisher"
    restart: always

  subscriber:
    build: ./subscriber
    environment:
      DEBUG_ON: no
    ports:
      - "6002:8080"
  subscriber_dapr:
    build: ./dapr
    command: /daprd -app-id subscriber --log-level debug --app-port 8080 --resources-path /components
    network_mode: "service:subscriber"
    restart: always