apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis_service:6379
  - name: redisPassword
    value: S0m3P@$$w0rd
scopes:
  - publisher
  - bulk-publisher
  - subscriber
  - publisher-tracing